/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ApiInstagramUserReelsGetUserIdParameter
 * 
 * @export
 */
export type ApiInstagramUserReelsGetUserIdParameter = number | string;

export function ApiInstagramUserReelsGetUserIdParameterFromJSON(json: any): ApiInstagramUserReelsGetUserIdParameter {
    return ApiInstagramUserReelsGetUserIdParameterFromJSONTyped(json, false);
}

export function ApiInstagramUserReelsGetUserIdParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiInstagramUserReelsGetUserIdParameter {
    if (json == null) {
        return json;
    }

    return {} as any;
}

export function ApiInstagramUserReelsGetUserIdParameterToJSON(json: any): any {
    return ApiInstagramUserReelsGetUserIdParameterToJSONTyped(json, false);
}

export function ApiInstagramUserReelsGetUserIdParameterToJSONTyped(value?: ApiInstagramUserReelsGetUserIdParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {};
}

