/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiInstagramUserReelsGetUserIdParameter } from './ApiInstagramUserReelsGetUserIdParameter';
import {
    ApiInstagramUserReelsGetUserIdParameterFromJSON,
    ApiInstagramUserReelsGetUserIdParameterFromJSONTyped,
    ApiInstagramUserReelsGetUserIdParameterToJSON,
    ApiInstagramUserReelsGetUserIdParameterToJSONTyped,
} from './ApiInstagramUserReelsGetUserIdParameter';

/**
 * 
 * @export
 * @interface ApiInstagramUserReelsPostRequest
 */
export interface ApiInstagramUserReelsPostRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {ApiInstagramUserReelsGetUserIdParameter}
     * @memberof ApiInstagramUserReelsPostRequest
     */
    userId: ApiInstagramUserReelsGetUserIdParameter;
    /**
     * 
     * @type {string}
     * @memberof ApiInstagramUserReelsPostRequest
     */
    username?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiInstagramUserReelsPostRequest
     */
    count?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApiInstagramUserReelsPostRequest
     */
    includeFeedVideo?: boolean;
}

/**
 * Check if a given object implements the ApiInstagramUserReelsPostRequest interface.
 */
export function instanceOfApiInstagramUserReelsPostRequest(value: object): value is ApiInstagramUserReelsPostRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function ApiInstagramUserReelsPostRequestFromJSON(json: any): ApiInstagramUserReelsPostRequest {
    return ApiInstagramUserReelsPostRequestFromJSONTyped(json, false);
}

export function ApiInstagramUserReelsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiInstagramUserReelsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'userId': ApiInstagramUserReelsGetUserIdParameterFromJSON(json['userId']),
        'username': json['username'] == null ? undefined : json['username'],
        'count': json['count'] == null ? undefined : json['count'],
        'includeFeedVideo': json['includeFeedVideo'] == null ? undefined : json['includeFeedVideo'],
    };
}

export function ApiInstagramUserReelsPostRequestToJSON(json: any): ApiInstagramUserReelsPostRequest {
    return ApiInstagramUserReelsPostRequestToJSONTyped(json, false);
}

export function ApiInstagramUserReelsPostRequestToJSONTyped(value?: ApiInstagramUserReelsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'userId': ApiInstagramUserReelsGetUserIdParameterToJSON(value['userId']),
        'username': value['username'],
        'count': value['count'],
        'includeFeedVideo': value['includeFeedVideo'],
    };
}

