/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiTiktokUserFeedPostRequest
 */
export interface ApiTiktokUserFeedPostRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ApiTiktokUserFeedPostRequest
     */
    username: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTiktokUserFeedPostRequest
     */
    count?: number;
}

/**
 * Check if a given object implements the ApiTiktokUserFeedPostRequest interface.
 */
export function instanceOfApiTiktokUserFeedPostRequest(value: object): value is ApiTiktokUserFeedPostRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function ApiTiktokUserFeedPostRequestFromJSON(json: any): ApiTiktokUserFeedPostRequest {
    return ApiTiktokUserFeedPostRequestFromJSONTyped(json, false);
}

export function ApiTiktokUserFeedPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTiktokUserFeedPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'username': json['username'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function ApiTiktokUserFeedPostRequestToJSON(json: any): ApiTiktokUserFeedPostRequest {
    return ApiTiktokUserFeedPostRequestToJSONTyped(json, false);
}

export function ApiTiktokUserFeedPostRequestToJSONTyped(value?: ApiTiktokUserFeedPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'username': value['username'],
        'count': value['count'],
    };
}

