/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiVideoScrapeUrlPost200ResponseResult } from './ApiVideoScrapeUrlPost200ResponseResult';
import {
    ApiVideoScrapeUrlPost200ResponseResultFromJSON,
    ApiVideoScrapeUrlPost200ResponseResultFromJSONTyped,
    ApiVideoScrapeUrlPost200ResponseResultToJSON,
    ApiVideoScrapeUrlPost200ResponseResultToJSONTyped,
} from './ApiVideoScrapeUrlPost200ResponseResult';

/**
 * 
 * @export
 * @interface ApiVideoScrapeUrlPost200Response
 */
export interface ApiVideoScrapeUrlPost200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof ApiVideoScrapeUrlPost200Response
     */
    success: boolean;
    /**
     * 
     * @type {ApiVideoScrapeUrlPost200ResponseResult}
     * @memberof ApiVideoScrapeUrlPost200Response
     */
    result?: ApiVideoScrapeUrlPost200ResponseResult;
}

/**
 * Check if a given object implements the ApiVideoScrapeUrlPost200Response interface.
 */
export function instanceOfApiVideoScrapeUrlPost200Response(value: object): value is ApiVideoScrapeUrlPost200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ApiVideoScrapeUrlPost200ResponseFromJSON(json: any): ApiVideoScrapeUrlPost200Response {
    return ApiVideoScrapeUrlPost200ResponseFromJSONTyped(json, false);
}

export function ApiVideoScrapeUrlPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVideoScrapeUrlPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
        'result': json['result'] == null ? undefined : ApiVideoScrapeUrlPost200ResponseResultFromJSON(json['result']),
    };
}

export function ApiVideoScrapeUrlPost200ResponseToJSON(json: any): ApiVideoScrapeUrlPost200Response {
    return ApiVideoScrapeUrlPost200ResponseToJSONTyped(json, false);
}

export function ApiVideoScrapeUrlPost200ResponseToJSONTyped(value?: ApiVideoScrapeUrlPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
        'result': ApiVideoScrapeUrlPost200ResponseResultToJSON(value['result']),
    };
}

