/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVideosCollectionPostRequest
 */
export interface ApiVideosCollectionPostRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ApiVideosCollectionPostRequest
     */
    collectionId?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiVideosCollectionPostRequest
     */
    videoLimit?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVideosCollectionPostRequest
     */
    lastDocId?: string;
}

/**
 * Check if a given object implements the ApiVideosCollectionPostRequest interface.
 */
export function instanceOfApiVideosCollectionPostRequest(value: object): value is ApiVideosCollectionPostRequest {
    return true;
}

export function ApiVideosCollectionPostRequestFromJSON(json: any): ApiVideosCollectionPostRequest {
    return ApiVideosCollectionPostRequestFromJSONTyped(json, false);
}

export function ApiVideosCollectionPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVideosCollectionPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'collectionId': json['collectionId'] == null ? undefined : json['collectionId'],
        'videoLimit': json['videoLimit'] == null ? undefined : json['videoLimit'],
        'lastDocId': json['lastDocId'] == null ? undefined : json['lastDocId'],
    };
}

export function ApiVideosCollectionPostRequestToJSON(json: any): ApiVideosCollectionPostRequest {
    return ApiVideosCollectionPostRequestToJSONTyped(json, false);
}

export function ApiVideosCollectionPostRequestToJSONTyped(value?: ApiVideosCollectionPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'collectionId': value['collectionId'],
        'videoLimit': value['videoLimit'],
        'lastDocId': value['lastDocId'],
    };
}

