/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVideoScrapeUrlPost200ResponseResult
 */
export interface ApiVideoScrapeUrlPost200ResponseResult {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoScrapeUrlPost200ResponseResult
     */
    downloadUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoScrapeUrlPost200ResponseResult
     */
    audioUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoScrapeUrlPost200ResponseResult
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoScrapeUrlPost200ResponseResult
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoScrapeUrlPost200ResponseResult
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoScrapeUrlPost200ResponseResult
     */
    author?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiVideoScrapeUrlPost200ResponseResult
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiVideoScrapeUrlPost200ResponseResult
     */
    platform?: ApiVideoScrapeUrlPost200ResponseResultPlatformEnum;
}


/**
 * @export
 */
export const ApiVideoScrapeUrlPost200ResponseResultPlatformEnum = {
    Tiktok: 'tiktok',
    Instagram: 'instagram'
} as const;
export type ApiVideoScrapeUrlPost200ResponseResultPlatformEnum = typeof ApiVideoScrapeUrlPost200ResponseResultPlatformEnum[keyof typeof ApiVideoScrapeUrlPost200ResponseResultPlatformEnum];


/**
 * Check if a given object implements the ApiVideoScrapeUrlPost200ResponseResult interface.
 */
export function instanceOfApiVideoScrapeUrlPost200ResponseResult(value: object): value is ApiVideoScrapeUrlPost200ResponseResult {
    return true;
}

export function ApiVideoScrapeUrlPost200ResponseResultFromJSON(json: any): ApiVideoScrapeUrlPost200ResponseResult {
    return ApiVideoScrapeUrlPost200ResponseResultFromJSONTyped(json, false);
}

export function ApiVideoScrapeUrlPost200ResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVideoScrapeUrlPost200ResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'downloadUrl': json['downloadUrl'] == null ? undefined : json['downloadUrl'],
        'audioUrl': json['audioUrl'] == null ? undefined : json['audioUrl'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'author': json['author'] == null ? undefined : json['author'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'platform': json['platform'] == null ? undefined : json['platform'],
    };
}

export function ApiVideoScrapeUrlPost200ResponseResultToJSON(json: any): ApiVideoScrapeUrlPost200ResponseResult {
    return ApiVideoScrapeUrlPost200ResponseResultToJSONTyped(json, false);
}

export function ApiVideoScrapeUrlPost200ResponseResultToJSONTyped(value?: ApiVideoScrapeUrlPost200ResponseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'downloadUrl': value['downloadUrl'],
        'audioUrl': value['audioUrl'],
        'thumbnailUrl': value['thumbnailUrl'],
        'title': value['title'],
        'description': value['description'],
        'author': value['author'],
        'duration': value['duration'],
        'platform': value['platform'],
    };
}

