/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiVideosAddToCollectionPost200Response
 */
export interface ApiVideosAddToCollectionPost200Response {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof ApiVideosAddToCollectionPost200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiVideosAddToCollectionPost200Response
     */
    videoId?: string;
}

/**
 * Check if a given object implements the ApiVideosAddToCollectionPost200Response interface.
 */
export function instanceOfApiVideosAddToCollectionPost200Response(value: object): value is ApiVideosAddToCollectionPost200Response {
    return true;
}

export function ApiVideosAddToCollectionPost200ResponseFromJSON(json: any): ApiVideosAddToCollectionPost200Response {
    return ApiVideosAddToCollectionPost200ResponseFromJSONTyped(json, false);
}

export function ApiVideosAddToCollectionPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiVideosAddToCollectionPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'] == null ? undefined : json['success'],
        'videoId': json['videoId'] == null ? undefined : json['videoId'],
    };
}

export function ApiVideosAddToCollectionPost200ResponseToJSON(json: any): ApiVideosAddToCollectionPost200Response {
    return ApiVideosAddToCollectionPost200ResponseToJSONTyped(json, false);
}

export function ApiVideosAddToCollectionPost200ResponseToJSONTyped(value?: ApiVideosAddToCollectionPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
        'videoId': value['videoId'],
    };
}

