/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BasicSuccessResponse
 */
export interface BasicSuccessResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof BasicSuccessResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the BasicSuccessResponse interface.
 */
export function instanceOfBasicSuccessResponse(value: object): value is BasicSuccessResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function BasicSuccessResponseFromJSON(json: any): BasicSuccessResponse {
    return BasicSuccessResponseFromJSONTyped(json, false);
}

export function BasicSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
    };
}

export function BasicSuccessResponseToJSON(json: any): BasicSuccessResponse {
    return BasicSuccessResponseToJSONTyped(json, false);
}

export function BasicSuccessResponseToJSONTyped(value?: BasicSuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
    };
}

