/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Collection
 */
export interface Collection {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof Collection
     */
    videoCount?: number;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Collection
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the Collection interface.
 */
export function instanceOfCollection(value: object): value is Collection {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function CollectionFromJSON(json: any): Collection {
    return CollectionFromJSONTyped(json, false);
}

export function CollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Collection {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'userId': json['userId'],
        'videoCount': json['videoCount'] == null ? undefined : json['videoCount'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'updatedAt': json['updatedAt'] == null ? undefined : json['updatedAt'],
    };
}

export function CollectionToJSON(json: any): Collection {
    return CollectionToJSONTyped(json, false);
}

export function CollectionToJSONTyped(value?: Collection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'userId': value['userId'],
        'videoCount': value['videoCount'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

