/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Collection } from './Collection';
import {
    CollectionFromJSON,
    CollectionFromJSONTyped,
    CollectionToJSON,
    CollectionToJSONTyped,
} from './Collection';

/**
 * 
 * @export
 * @interface CollectionsResponse
 */
export interface CollectionsResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof CollectionsResponse
     */
    success: boolean;
    /**
     * 
     * @type {Array<Collection>}
     * @memberof CollectionsResponse
     */
    collections?: Array<Collection>;
}

/**
 * Check if a given object implements the CollectionsResponse interface.
 */
export function instanceOfCollectionsResponse(value: object): value is CollectionsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function CollectionsResponseFromJSON(json: any): CollectionsResponse {
    return CollectionsResponseFromJSONTyped(json, false);
}

export function CollectionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
        'collections': json['collections'] == null ? undefined : ((json['collections'] as Array<any>).map(CollectionFromJSON)),
    };
}

export function CollectionsResponseToJSON(json: any): CollectionsResponse {
    return CollectionsResponseToJSONTyped(json, false);
}

export function CollectionsResponseToJSONTyped(value?: CollectionsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
        'collections': value['collections'] == null ? undefined : ((value['collections'] as Array<any>).map(CollectionToJSON)),
    };
}

