/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CopyVideoRequest
 */
export interface CopyVideoRequest {
    /**
     * 
     * @type {string}
     * @memberof CopyVideoRequest
     */
    videoId: string;
    /**
     * 
     * @type {string}
     * @memberof CopyVideoRequest
     */
    fromCollectionId?: string;
    /**
     * 
     * @type {string}
     * @memberof CopyVideoRequest
     */
    toCollectionId: string;
}

/**
 * Check if a given object implements the CopyVideoRequest interface.
 */
export function instanceOfCopyVideoRequest(value: object): value is CopyVideoRequest {
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    if (!('toCollectionId' in value) || value['toCollectionId'] === undefined) return false;
    return true;
}

export function CopyVideoRequestFromJSON(json: any): CopyVideoRequest {
    return CopyVideoRequestFromJSONTyped(json, false);
}

export function CopyVideoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CopyVideoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'videoId': json['videoId'],
        'fromCollectionId': json['fromCollectionId'] == null ? undefined : json['fromCollectionId'],
        'toCollectionId': json['toCollectionId'],
    };
}

export function CopyVideoRequestToJSON(json: any): CopyVideoRequest {
    return CopyVideoRequestToJSONTyped(json, false);
}

export function CopyVideoRequestToJSONTyped(value?: CopyVideoRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'videoId': value['videoId'],
        'fromCollectionId': value['fromCollectionId'],
        'toCollectionId': value['toCollectionId'],
    };
}

