/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNoteRequest
 */
export interface CreateNoteRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof CreateNoteRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateNoteRequest
     */
    content: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateNoteRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateNoteRequest
     */
    starred?: boolean;
}

/**
 * Check if a given object implements the CreateNoteRequest interface.
 */
export function instanceOfCreateNoteRequest(value: object): value is CreateNoteRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateNoteRequestFromJSON(json: any): CreateNoteRequest {
    return CreateNoteRequestFromJSONTyped(json, false);
}

export function CreateNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'title': json['title'],
        'content': json['content'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'starred': json['starred'] == null ? undefined : json['starred'],
    };
}

export function CreateNoteRequestToJSON(json: any): CreateNoteRequest {
    return CreateNoteRequestToJSONTyped(json, false);
}

export function CreateNoteRequestToJSONTyped(value?: CreateNoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'title': value['title'],
        'content': value['content'],
        'tags': value['tags'],
        'starred': value['starred'],
    };
}

