/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateIdeaSeedsResponseMeta
 */
export interface GenerateIdeaSeedsResponseMeta {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof GenerateIdeaSeedsResponseMeta
     */
    model?: string;
    /**
     * 
     * @type {number}
     * @memberof GenerateIdeaSeedsResponseMeta
     */
    durationMs?: number;
    /**
     * 
     * @type {number}
     * @memberof GenerateIdeaSeedsResponseMeta
     */
    maxIdeas?: number;
    /**
     * 
     * @type {number}
     * @memberof GenerateIdeaSeedsResponseMeta
     */
    minOverall?: number;
    /**
     * 
     * @type {string}
     * @memberof GenerateIdeaSeedsResponseMeta
     */
    audienceLevel?: string;
    /**
     * 
     * @type {number}
     * @memberof GenerateIdeaSeedsResponseMeta
     */
    transcriptChars?: number;
}

/**
 * Check if a given object implements the GenerateIdeaSeedsResponseMeta interface.
 */
export function instanceOfGenerateIdeaSeedsResponseMeta(value: object): value is GenerateIdeaSeedsResponseMeta {
    return true;
}

export function GenerateIdeaSeedsResponseMetaFromJSON(json: any): GenerateIdeaSeedsResponseMeta {
    return GenerateIdeaSeedsResponseMetaFromJSONTyped(json, false);
}

export function GenerateIdeaSeedsResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateIdeaSeedsResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'model': json['model'] == null ? undefined : json['model'],
        'durationMs': json['durationMs'] == null ? undefined : json['durationMs'],
        'maxIdeas': json['maxIdeas'] == null ? undefined : json['maxIdeas'],
        'minOverall': json['minOverall'] == null ? undefined : json['minOverall'],
        'audienceLevel': json['audienceLevel'] == null ? undefined : json['audienceLevel'],
        'transcriptChars': json['transcriptChars'] == null ? undefined : json['transcriptChars'],
    };
}

export function GenerateIdeaSeedsResponseMetaToJSON(json: any): GenerateIdeaSeedsResponseMeta {
    return GenerateIdeaSeedsResponseMetaToJSONTyped(json, false);
}

export function GenerateIdeaSeedsResponseMetaToJSONTyped(value?: GenerateIdeaSeedsResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'model': value['model'],
        'durationMs': value['durationMs'],
        'maxIdeas': value['maxIdeas'],
        'minOverall': value['minOverall'],
        'audienceLevel': value['audienceLevel'],
        'transcriptChars': value['transcriptChars'],
    };
}

