/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdeaSeedCtaTargetOneOf
 */
export interface IdeaSeedCtaTargetOneOf {
    /**
     * 
     * @type {number}
     * @memberof IdeaSeedCtaTargetOneOf
     */
    videoTs: number;
}

/**
 * Check if a given object implements the IdeaSeedCtaTargetOneOf interface.
 */
export function instanceOfIdeaSeedCtaTargetOneOf(value: object): value is IdeaSeedCtaTargetOneOf {
    if (!('videoTs' in value) || value['videoTs'] === undefined) return false;
    return true;
}

export function IdeaSeedCtaTargetOneOfFromJSON(json: any): IdeaSeedCtaTargetOneOf {
    return IdeaSeedCtaTargetOneOfFromJSONTyped(json, false);
}

export function IdeaSeedCtaTargetOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaSeedCtaTargetOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'videoTs': json['videoTs'],
    };
}

export function IdeaSeedCtaTargetOneOfToJSON(json: any): IdeaSeedCtaTargetOneOf {
    return IdeaSeedCtaTargetOneOfToJSONTyped(json, false);
}

export function IdeaSeedCtaTargetOneOfToJSONTyped(value?: IdeaSeedCtaTargetOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'videoTs': value['videoTs'],
    };
}

