/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IdeaSeedProvenance
 */
export interface IdeaSeedProvenance {
    /**
     * 
     * @type {number}
     * @memberof IdeaSeedProvenance
     */
    startSec: number;
    /**
     * 
     * @type {number}
     * @memberof IdeaSeedProvenance
     */
    endSec: number;
}

/**
 * Check if a given object implements the IdeaSeedProvenance interface.
 */
export function instanceOfIdeaSeedProvenance(value: object): value is IdeaSeedProvenance {
    if (!('startSec' in value) || value['startSec'] === undefined) return false;
    if (!('endSec' in value) || value['endSec'] === undefined) return false;
    return true;
}

export function IdeaSeedProvenanceFromJSON(json: any): IdeaSeedProvenance {
    return IdeaSeedProvenanceFromJSONTyped(json, false);
}

export function IdeaSeedProvenanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaSeedProvenance {
    if (json == null) {
        return json;
    }
    return {
        
        'startSec': json['startSec'],
        'endSec': json['endSec'],
    };
}

export function IdeaSeedProvenanceToJSON(json: any): IdeaSeedProvenance {
    return IdeaSeedProvenanceToJSONTyped(json, false);
}

export function IdeaSeedProvenanceToJSONTyped(value?: IdeaSeedProvenance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startSec': value['startSec'],
        'endSec': value['endSec'],
    };
}

