/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { IdeaSeedCtaTargetOneOf } from './IdeaSeedCtaTargetOneOf';
import {
    instanceOfIdeaSeedCtaTargetOneOf,
    IdeaSeedCtaTargetOneOfFromJSON,
    IdeaSeedCtaTargetOneOfFromJSONTyped,
    IdeaSeedCtaTargetOneOfToJSON,
} from './IdeaSeedCtaTargetOneOf';

/**
 * @type IdeaSeedCtaTarget
 * 
 * @export
 */
export type IdeaSeedCtaTarget = IdeaSeedCtaTargetOneOf | string;

export function IdeaSeedCtaTargetFromJSON(json: any): IdeaSeedCtaTarget {
    return IdeaSeedCtaTargetFromJSONTyped(json, false);
}

export function IdeaSeedCtaTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdeaSeedCtaTarget {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfIdeaSeedCtaTargetOneOf(json)) {
        return IdeaSeedCtaTargetOneOfFromJSONTyped(json, true);
    }

    return {} as any;
}

export function IdeaSeedCtaTargetToJSON(json: any): any {
    return IdeaSeedCtaTargetToJSONTyped(json, false);
}

export function IdeaSeedCtaTargetToJSONTyped(value?: IdeaSeedCtaTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfIdeaSeedCtaTargetOneOf(value)) {
        return IdeaSeedCtaTargetOneOfToJSON(value as IdeaSeedCtaTargetOneOf);
    }

    return {};
}

