/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiInstagramUserReelsGetUserIdParameter } from './ApiInstagramUserReelsGetUserIdParameter';
import {
    ApiInstagramUserReelsGetUserIdParameterFromJSON,
    ApiInstagramUserReelsGetUserIdParameterFromJSONTyped,
    ApiInstagramUserReelsGetUserIdParameterToJSON,
    ApiInstagramUserReelsGetUserIdParameterToJSONTyped,
} from './ApiInstagramUserReelsGetUserIdParameter';

/**
 * 
 * @export
 * @interface InstagramUserIdResponse
 */
export interface InstagramUserIdResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof InstagramUserIdResponse
     */
    success: boolean;
    /**
     * 
     * @type {ApiInstagramUserReelsGetUserIdParameter}
     * @memberof InstagramUserIdResponse
     */
    userId: ApiInstagramUserReelsGetUserIdParameter;
    /**
     * 
     * @type {string}
     * @memberof InstagramUserIdResponse
     */
    username: string;
}

/**
 * Check if a given object implements the InstagramUserIdResponse interface.
 */
export function instanceOfInstagramUserIdResponse(value: object): value is InstagramUserIdResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function InstagramUserIdResponseFromJSON(json: any): InstagramUserIdResponse {
    return InstagramUserIdResponseFromJSONTyped(json, false);
}

export function InstagramUserIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramUserIdResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
        'userId': ApiInstagramUserReelsGetUserIdParameterFromJSON(json['user_id']),
        'username': json['username'],
    };
}

export function InstagramUserIdResponseToJSON(json: any): InstagramUserIdResponse {
    return InstagramUserIdResponseToJSONTyped(json, false);
}

export function InstagramUserIdResponseToJSONTyped(value?: InstagramUserIdResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
        'user_id': ApiInstagramUserReelsGetUserIdParameterToJSON(value['userId']),
        'username': value['username'],
    };
}

