/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstagramReelsResponseData } from './InstagramReelsResponseData';
import {
    InstagramReelsResponseDataFromJSON,
    InstagramReelsResponseDataFromJSONTyped,
    InstagramReelsResponseDataToJSON,
    InstagramReelsResponseDataToJSONTyped,
} from './InstagramReelsResponseData';
import type { InstagramReelsResponseProcessed } from './InstagramReelsResponseProcessed';
import {
    InstagramReelsResponseProcessedFromJSON,
    InstagramReelsResponseProcessedFromJSONTyped,
    InstagramReelsResponseProcessedToJSON,
    InstagramReelsResponseProcessedToJSONTyped,
} from './InstagramReelsResponseProcessed';

/**
 * 
 * @export
 * @interface InstagramReelsResponse
 */
export interface InstagramReelsResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof InstagramReelsResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof InstagramReelsResponse
     */
    status?: string;
    /**
     * 
     * @type {InstagramReelsResponseData}
     * @memberof InstagramReelsResponse
     */
    data?: InstagramReelsResponseData;
    /**
     * 
     * @type {InstagramReelsResponseProcessed}
     * @memberof InstagramReelsResponse
     */
    processed?: InstagramReelsResponseProcessed;
}

/**
 * Check if a given object implements the InstagramReelsResponse interface.
 */
export function instanceOfInstagramReelsResponse(value: object): value is InstagramReelsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function InstagramReelsResponseFromJSON(json: any): InstagramReelsResponse {
    return InstagramReelsResponseFromJSONTyped(json, false);
}

export function InstagramReelsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramReelsResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : InstagramReelsResponseDataFromJSON(json['data']),
        'processed': json['processed'] == null ? undefined : InstagramReelsResponseProcessedFromJSON(json['processed']),
    };
}

export function InstagramReelsResponseToJSON(json: any): InstagramReelsResponse {
    return InstagramReelsResponseToJSONTyped(json, false);
}

export function InstagramReelsResponseToJSONTyped(value?: InstagramReelsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
        'status': value['status'],
        'data': InstagramReelsResponseDataToJSON(value['data']),
        'processed': InstagramReelsResponseProcessedToJSON(value['processed']),
    };
}

