/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstagramReelsResponseData
 */
export interface InstagramReelsResponseData {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof InstagramReelsResponseData
     */
    items?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the InstagramReelsResponseData interface.
 */
export function instanceOfInstagramReelsResponseData(value: object): value is InstagramReelsResponseData {
    return true;
}

export function InstagramReelsResponseDataFromJSON(json: any): InstagramReelsResponseData {
    return InstagramReelsResponseDataFromJSONTyped(json, false);
}

export function InstagramReelsResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramReelsResponseData {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'items': json['items'] == null ? undefined : json['items'],
    };
}

export function InstagramReelsResponseDataToJSON(json: any): InstagramReelsResponseData {
    return InstagramReelsResponseDataToJSONTyped(json, false);
}

export function InstagramReelsResponseDataToJSONTyped(value?: InstagramReelsResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'items': value['items'],
    };
}

