/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstagramProfileData
 */
export interface InstagramProfileData {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof InstagramProfileData
     */
    profileImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProfileData
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProfileData
     */
    bio?: string;
    /**
     * 
     * @type {number}
     * @memberof InstagramProfileData
     */
    followersCount?: number;
    /**
     * 
     * @type {number}
     * @memberof InstagramProfileData
     */
    followingCount?: number;
    /**
     * 
     * @type {number}
     * @memberof InstagramProfileData
     */
    postsCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InstagramProfileData
     */
    isVerified?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InstagramProfileData
     */
    isPrivate?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InstagramProfileData
     */
    externalUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProfileData
     */
    category?: string;
}

/**
 * Check if a given object implements the InstagramProfileData interface.
 */
export function instanceOfInstagramProfileData(value: object): value is InstagramProfileData {
    return true;
}

export function InstagramProfileDataFromJSON(json: any): InstagramProfileData {
    return InstagramProfileDataFromJSONTyped(json, false);
}

export function InstagramProfileDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramProfileData {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'profileImageUrl': json['profileImageUrl'] == null ? undefined : json['profileImageUrl'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'followersCount': json['followersCount'] == null ? undefined : json['followersCount'],
        'followingCount': json['followingCount'] == null ? undefined : json['followingCount'],
        'postsCount': json['postsCount'] == null ? undefined : json['postsCount'],
        'isVerified': json['isVerified'] == null ? undefined : json['isVerified'],
        'isPrivate': json['isPrivate'] == null ? undefined : json['isPrivate'],
        'externalUrl': json['externalUrl'] == null ? undefined : json['externalUrl'],
        'category': json['category'] == null ? undefined : json['category'],
    };
}

export function InstagramProfileDataToJSON(json: any): InstagramProfileData {
    return InstagramProfileDataToJSONTyped(json, false);
}

export function InstagramProfileDataToJSONTyped(value?: InstagramProfileData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'profileImageUrl': value['profileImageUrl'],
        'displayName': value['displayName'],
        'bio': value['bio'],
        'followersCount': value['followersCount'],
        'followingCount': value['followingCount'],
        'postsCount': value['postsCount'],
        'isVerified': value['isVerified'],
        'isPrivate': value['isPrivate'],
        'externalUrl': value['externalUrl'],
        'category': value['category'],
    };
}

