/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstagramProcessedVideo
 */
export interface InstagramProcessedVideo {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    platform?: InstagramProcessedVideoPlatformEnum;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    videoUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    downloadUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    playUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    thumbnailUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof InstagramProcessedVideo
     */
    viewCount?: number;
    /**
     * 
     * @type {number}
     * @memberof InstagramProcessedVideo
     */
    likeCount?: number;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    quality?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof InstagramProcessedVideo
     */
    author?: string;
    /**
     * 
     * @type {number}
     * @memberof InstagramProcessedVideo
     */
    duration?: number;
}


/**
 * @export
 */
export const InstagramProcessedVideoPlatformEnum = {
    Instagram: 'instagram'
} as const;
export type InstagramProcessedVideoPlatformEnum = typeof InstagramProcessedVideoPlatformEnum[keyof typeof InstagramProcessedVideoPlatformEnum];


/**
 * Check if a given object implements the InstagramProcessedVideo interface.
 */
export function instanceOfInstagramProcessedVideo(value: object): value is InstagramProcessedVideo {
    return true;
}

export function InstagramProcessedVideoFromJSON(json: any): InstagramProcessedVideo {
    return InstagramProcessedVideoFromJSONTyped(json, false);
}

export function InstagramProcessedVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramProcessedVideo {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : json['id'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'videoUrl': json['videoUrl'] == null ? undefined : json['videoUrl'],
        'downloadUrl': json['downloadUrl'] == null ? undefined : json['downloadUrl'],
        'playUrl': json['playUrl'] == null ? undefined : json['playUrl'],
        'thumbnailUrl': json['thumbnailUrl'] == null ? undefined : json['thumbnailUrl'],
        'viewCount': json['viewCount'] == null ? undefined : json['viewCount'],
        'likeCount': json['likeCount'] == null ? undefined : json['likeCount'],
        'quality': json['quality'] == null ? undefined : json['quality'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'author': json['author'] == null ? undefined : json['author'],
        'duration': json['duration'] == null ? undefined : json['duration'],
    };
}

export function InstagramProcessedVideoToJSON(json: any): InstagramProcessedVideo {
    return InstagramProcessedVideoToJSONTyped(json, false);
}

export function InstagramProcessedVideoToJSONTyped(value?: InstagramProcessedVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'platform': value['platform'],
        'videoUrl': value['videoUrl'],
        'downloadUrl': value['downloadUrl'],
        'playUrl': value['playUrl'],
        'thumbnailUrl': value['thumbnailUrl'],
        'viewCount': value['viewCount'],
        'likeCount': value['likeCount'],
        'quality': value['quality'],
        'title': value['title'],
        'description': value['description'],
        'author': value['author'],
        'duration': value['duration'],
    };
}

