/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InstagramProfileData } from './InstagramProfileData';
import {
    InstagramProfileDataFromJSON,
    InstagramProfileDataFromJSONTyped,
    InstagramProfileDataToJSON,
    InstagramProfileDataToJSONTyped,
} from './InstagramProfileData';
import type { InstagramProcessedVideo } from './InstagramProcessedVideo';
import {
    InstagramProcessedVideoFromJSON,
    InstagramProcessedVideoFromJSONTyped,
    InstagramProcessedVideoToJSON,
    InstagramProcessedVideoToJSONTyped,
} from './InstagramProcessedVideo';

/**
 * 
 * @export
 * @interface InstagramReelsResponseProcessed
 */
export interface InstagramReelsResponseProcessed {
    [key: string]: any | any;
    /**
     * 
     * @type {Array<InstagramProcessedVideo>}
     * @memberof InstagramReelsResponseProcessed
     */
    videos?: Array<InstagramProcessedVideo>;
    /**
     * 
     * @type {InstagramProfileData}
     * @memberof InstagramReelsResponseProcessed
     */
    profileData?: InstagramProfileData;
    /**
     * 
     * @type {number}
     * @memberof InstagramReelsResponseProcessed
     */
    totalFound?: number;
}

/**
 * Check if a given object implements the InstagramReelsResponseProcessed interface.
 */
export function instanceOfInstagramReelsResponseProcessed(value: object): value is InstagramReelsResponseProcessed {
    return true;
}

export function InstagramReelsResponseProcessedFromJSON(json: any): InstagramReelsResponseProcessed {
    return InstagramReelsResponseProcessedFromJSONTyped(json, false);
}

export function InstagramReelsResponseProcessedFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstagramReelsResponseProcessed {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'videos': json['videos'] == null ? undefined : ((json['videos'] as Array<any>).map(InstagramProcessedVideoFromJSON)),
        'profileData': json['profileData'] == null ? undefined : InstagramProfileDataFromJSON(json['profileData']),
        'totalFound': json['totalFound'] == null ? undefined : json['totalFound'],
    };
}

export function InstagramReelsResponseProcessedToJSON(json: any): InstagramReelsResponseProcessed {
    return InstagramReelsResponseProcessedToJSONTyped(json, false);
}

export function InstagramReelsResponseProcessedToJSONTyped(value?: InstagramReelsResponseProcessed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'videos': value['videos'] == null ? undefined : ((value['videos'] as Array<any>).map(InstagramProcessedVideoToJSON)),
        'profileData': InstagramProfileDataToJSON(value['profileData']),
        'totalFound': value['totalFound'],
    };
}

