/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Note } from './Note';
import {
    NoteFromJSON,
    NoteFromJSONTyped,
    NoteToJSON,
    NoteToJSONTyped,
} from './Note';

/**
 * 
 * @export
 * @interface NoteResponse
 */
export interface NoteResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof NoteResponse
     */
    success: boolean;
    /**
     * 
     * @type {Note}
     * @memberof NoteResponse
     */
    note?: Note;
}

/**
 * Check if a given object implements the NoteResponse interface.
 */
export function instanceOfNoteResponse(value: object): value is NoteResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function NoteResponseFromJSON(json: any): NoteResponse {
    return NoteResponseFromJSONTyped(json, false);
}

export function NoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoteResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
        'note': json['note'] == null ? undefined : NoteFromJSON(json['note']),
    };
}

export function NoteResponseToJSON(json: any): NoteResponse {
    return NoteResponseToJSONTyped(json, false);
}

export function NoteResponseToJSONTyped(value?: NoteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
        'note': NoteToJSON(value['note']),
    };
}

