/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Note
 */
export interface Note {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    content: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Note
     */
    tags?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof Note
     */
    starred?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof Note
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the Note interface.
 */
export function instanceOfNote(value: object): value is Note {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function NoteFromJSON(json: any): Note {
    return NoteFromJSONTyped(json, false);
}

export function NoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Note {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'],
        'title': json['title'],
        'content': json['content'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'starred': json['starred'] == null ? undefined : json['starred'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
    };
}

export function NoteToJSON(json: any): Note {
    return NoteToJSONTyped(json, false);
}

export function NoteToJSONTyped(value?: Note | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'tags': value['tags'],
        'starred': value['starred'],
        'userId': value['userId'],
        'createdAt': value['createdAt'],
        'updatedAt': value['updatedAt'],
    };
}

