/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrchestrateRequestOptions
 */
export interface OrchestrateRequestOptions {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof OrchestrateRequestOptions
     */
    transcribe?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrchestrateRequestOptions
     */
    preferAudioOnly?: boolean;
}

/**
 * Check if a given object implements the OrchestrateRequestOptions interface.
 */
export function instanceOfOrchestrateRequestOptions(value: object): value is OrchestrateRequestOptions {
    return true;
}

export function OrchestrateRequestOptionsFromJSON(json: any): OrchestrateRequestOptions {
    return OrchestrateRequestOptionsFromJSONTyped(json, false);
}

export function OrchestrateRequestOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrchestrateRequestOptions {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'transcribe': json['transcribe'] == null ? undefined : json['transcribe'],
        'preferAudioOnly': json['preferAudioOnly'] == null ? undefined : json['preferAudioOnly'],
    };
}

export function OrchestrateRequestOptionsToJSON(json: any): OrchestrateRequestOptions {
    return OrchestrateRequestOptionsToJSONTyped(json, false);
}

export function OrchestrateRequestOptionsToJSONTyped(value?: OrchestrateRequestOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'transcribe': value['transcribe'],
        'preferAudioOnly': value['preferAudioOnly'],
    };
}

