/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrchestrateResponse
 */
export interface OrchestrateResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof OrchestrateResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrchestrateResponse
     */
    videoId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrchestrateResponse
     */
    transcript?: string;
    /**
     * 
     * @type {string}
     * @memberof OrchestrateResponse
     */
    jobId?: string;
}

/**
 * Check if a given object implements the OrchestrateResponse interface.
 */
export function instanceOfOrchestrateResponse(value: object): value is OrchestrateResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function OrchestrateResponseFromJSON(json: any): OrchestrateResponse {
    return OrchestrateResponseFromJSONTyped(json, false);
}

export function OrchestrateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrchestrateResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
        'videoId': json['videoId'] == null ? undefined : json['videoId'],
        'transcript': json['transcript'] == null ? undefined : json['transcript'],
        'jobId': json['jobId'] == null ? undefined : json['jobId'],
    };
}

export function OrchestrateResponseToJSON(json: any): OrchestrateResponse {
    return OrchestrateResponseToJSONTyped(json, false);
}

export function OrchestrateResponseToJSONTyped(value?: OrchestrateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
        'videoId': value['videoId'],
        'transcript': value['transcript'],
        'jobId': value['jobId'],
    };
}

