/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScriptPerformance
 */
export interface ScriptPerformance {
    /**
     * 
     * @type {number}
     * @memberof ScriptPerformance
     */
    views?: number;
    /**
     * 
     * @type {number}
     * @memberof ScriptPerformance
     */
    engagement?: number;
}

/**
 * Check if a given object implements the ScriptPerformance interface.
 */
export function instanceOfScriptPerformance(value: object): value is ScriptPerformance {
    return true;
}

export function ScriptPerformanceFromJSON(json: any): ScriptPerformance {
    return ScriptPerformanceFromJSONTyped(json, false);
}

export function ScriptPerformanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScriptPerformance {
    if (json == null) {
        return json;
    }
    return {
        
        'views': json['views'] == null ? undefined : json['views'],
        'engagement': json['engagement'] == null ? undefined : json['engagement'],
    };
}

export function ScriptPerformanceToJSON(json: any): ScriptPerformance {
    return ScriptPerformanceToJSONTyped(json, false);
}

export function ScriptPerformanceToJSONTyped(value?: ScriptPerformance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'views': value['views'],
        'engagement': value['engagement'],
    };
}

