/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TikTokVideoStats } from './TikTokVideoStats';
import {
    TikTokVideoStatsFromJSON,
    TikTokVideoStatsFromJSONTyped,
    TikTokVideoStatsToJSON,
    TikTokVideoStatsToJSONTyped,
} from './TikTokVideoStats';

/**
 * 
 * @export
 * @interface TikTokVideo
 */
export interface TikTokVideo {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof TikTokVideo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TikTokVideo
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof TikTokVideo
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokVideo
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof TikTokVideo
     */
    cover?: string;
    /**
     * 
     * @type {string}
     * @memberof TikTokVideo
     */
    playUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof TikTokVideo
     */
    downloadUrl?: string;
    /**
     * 
     * @type {TikTokVideoStats}
     * @memberof TikTokVideo
     */
    stats?: TikTokVideoStats;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TikTokVideo
     */
    music?: { [key: string]: any; };
}

/**
 * Check if a given object implements the TikTokVideo interface.
 */
export function instanceOfTikTokVideo(value: object): value is TikTokVideo {
    return true;
}

export function TikTokVideoFromJSON(json: any): TikTokVideo {
    return TikTokVideoFromJSONTyped(json, false);
}

export function TikTokVideoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TikTokVideo {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : json['id'],
        'description': json['description'] == null ? undefined : json['description'],
        'createTime': json['createTime'] == null ? undefined : json['createTime'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'cover': json['cover'] == null ? undefined : json['cover'],
        'playUrl': json['playUrl'] == null ? undefined : json['playUrl'],
        'downloadUrl': json['downloadUrl'] == null ? undefined : json['downloadUrl'],
        'stats': json['stats'] == null ? undefined : TikTokVideoStatsFromJSON(json['stats']),
        'music': json['music'] == null ? undefined : json['music'],
    };
}

export function TikTokVideoToJSON(json: any): TikTokVideo {
    return TikTokVideoToJSONTyped(json, false);
}

export function TikTokVideoToJSONTyped(value?: TikTokVideo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'description': value['description'],
        'createTime': value['createTime'],
        'duration': value['duration'],
        'cover': value['cover'],
        'playUrl': value['playUrl'],
        'downloadUrl': value['downloadUrl'],
        'stats': TikTokVideoStatsToJSON(value['stats']),
        'music': value['music'],
    };
}

