/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TikTokUserInfoStats
 */
export interface TikTokUserInfoStats {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof TikTokUserInfoStats
     */
    followingCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokUserInfoStats
     */
    followerCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokUserInfoStats
     */
    heartCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokUserInfoStats
     */
    videoCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokUserInfoStats
     */
    diggCount?: number;
}

/**
 * Check if a given object implements the TikTokUserInfoStats interface.
 */
export function instanceOfTikTokUserInfoStats(value: object): value is TikTokUserInfoStats {
    return true;
}

export function TikTokUserInfoStatsFromJSON(json: any): TikTokUserInfoStats {
    return TikTokUserInfoStatsFromJSONTyped(json, false);
}

export function TikTokUserInfoStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TikTokUserInfoStats {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'followingCount': json['followingCount'] == null ? undefined : json['followingCount'],
        'followerCount': json['followerCount'] == null ? undefined : json['followerCount'],
        'heartCount': json['heartCount'] == null ? undefined : json['heartCount'],
        'videoCount': json['videoCount'] == null ? undefined : json['videoCount'],
        'diggCount': json['diggCount'] == null ? undefined : json['diggCount'],
    };
}

export function TikTokUserInfoStatsToJSON(json: any): TikTokUserInfoStats {
    return TikTokUserInfoStatsToJSONTyped(json, false);
}

export function TikTokUserInfoStatsToJSONTyped(value?: TikTokUserInfoStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'followingCount': value['followingCount'],
        'followerCount': value['followerCount'],
        'heartCount': value['heartCount'],
        'videoCount': value['videoCount'],
        'diggCount': value['diggCount'],
    };
}

