/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TikTokVideoStats
 */
export interface TikTokVideoStats {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof TikTokVideoStats
     */
    diggCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokVideoStats
     */
    shareCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokVideoStats
     */
    commentCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokVideoStats
     */
    playCount?: number;
    /**
     * 
     * @type {number}
     * @memberof TikTokVideoStats
     */
    collectCount?: number;
}

/**
 * Check if a given object implements the TikTokVideoStats interface.
 */
export function instanceOfTikTokVideoStats(value: object): value is TikTokVideoStats {
    return true;
}

export function TikTokVideoStatsFromJSON(json: any): TikTokVideoStats {
    return TikTokVideoStatsFromJSONTyped(json, false);
}

export function TikTokVideoStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TikTokVideoStats {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'diggCount': json['diggCount'] == null ? undefined : json['diggCount'],
        'shareCount': json['shareCount'] == null ? undefined : json['shareCount'],
        'commentCount': json['commentCount'] == null ? undefined : json['commentCount'],
        'playCount': json['playCount'] == null ? undefined : json['playCount'],
        'collectCount': json['collectCount'] == null ? undefined : json['collectCount'],
    };
}

export function TikTokVideoStatsToJSON(json: any): TikTokVideoStats {
    return TikTokVideoStatsToJSONTyped(json, false);
}

export function TikTokVideoStatsToJSONTyped(value?: TikTokVideoStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'diggCount': value['diggCount'],
        'shareCount': value['shareCount'],
        'commentCount': value['commentCount'],
        'playCount': value['playCount'],
        'collectCount': value['collectCount'],
    };
}

