/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TikTokUserInfo } from './TikTokUserInfo';
import {
    TikTokUserInfoFromJSON,
    TikTokUserInfoFromJSONTyped,
    TikTokUserInfoToJSON,
    TikTokUserInfoToJSONTyped,
} from './TikTokUserInfo';
import type { TikTokVideo } from './TikTokVideo';
import {
    TikTokVideoFromJSON,
    TikTokVideoFromJSONTyped,
    TikTokVideoToJSON,
    TikTokVideoToJSONTyped,
} from './TikTokVideo';

/**
 * 
 * @export
 * @interface TikTokUserFeedResponse
 */
export interface TikTokUserFeedResponse {
    [key: string]: any | any;
    /**
     * 
     * @type {boolean}
     * @memberof TikTokUserFeedResponse
     */
    success: boolean;
    /**
     * 
     * @type {TikTokUserInfo}
     * @memberof TikTokUserFeedResponse
     */
    userInfo?: TikTokUserInfo;
    /**
     * 
     * @type {Array<TikTokVideo>}
     * @memberof TikTokUserFeedResponse
     */
    videos?: Array<TikTokVideo>;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TikTokUserFeedResponse
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof TikTokUserFeedResponse
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the TikTokUserFeedResponse interface.
 */
export function instanceOfTikTokUserFeedResponse(value: object): value is TikTokUserFeedResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function TikTokUserFeedResponseFromJSON(json: any): TikTokUserFeedResponse {
    return TikTokUserFeedResponseFromJSONTyped(json, false);
}

export function TikTokUserFeedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TikTokUserFeedResponse {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'success': json['success'],
        'userInfo': json['userInfo'] == null ? undefined : TikTokUserInfoFromJSON(json['userInfo']),
        'videos': json['videos'] == null ? undefined : ((json['videos'] as Array<any>).map(TikTokVideoFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
    };
}

export function TikTokUserFeedResponseToJSON(json: any): TikTokUserFeedResponse {
    return TikTokUserFeedResponseToJSONTyped(json, false);
}

export function TikTokUserFeedResponseToJSONTyped(value?: TikTokUserFeedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'success': value['success'],
        'userInfo': TikTokUserInfoToJSON(value['userInfo']),
        'videos': value['videos'] == null ? undefined : ((value['videos'] as Array<any>).map(TikTokVideoToJSON)),
        'metadata': value['metadata'],
        'timestamp': value['timestamp'],
    };
}

