/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TikTokUserInfoStats } from './TikTokUserInfoStats';
import {
    TikTokUserInfoStatsFromJSON,
    TikTokUserInfoStatsFromJSONTyped,
    TikTokUserInfoStatsToJSON,
    TikTokUserInfoStatsToJSONTyped,
} from './TikTokUserInfoStats';

/**
 * 
 * @export
 * @interface TikTokUserInfo
 */
export interface TikTokUserInfo {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof TikTokUserInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof TikTokUserInfo
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof TikTokUserInfo
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof TikTokUserInfo
     */
    avatar?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TikTokUserInfo
     */
    verified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TikTokUserInfo
     */
    signature?: string;
    /**
     * 
     * @type {TikTokUserInfoStats}
     * @memberof TikTokUserInfo
     */
    stats?: TikTokUserInfoStats;
}

/**
 * Check if a given object implements the TikTokUserInfo interface.
 */
export function instanceOfTikTokUserInfo(value: object): value is TikTokUserInfo {
    return true;
}

export function TikTokUserInfoFromJSON(json: any): TikTokUserInfo {
    return TikTokUserInfoFromJSONTyped(json, false);
}

export function TikTokUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TikTokUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'verified': json['verified'] == null ? undefined : json['verified'],
        'signature': json['signature'] == null ? undefined : json['signature'],
        'stats': json['stats'] == null ? undefined : TikTokUserInfoStatsFromJSON(json['stats']),
    };
}

export function TikTokUserInfoToJSON(json: any): TikTokUserInfo {
    return TikTokUserInfoToJSONTyped(json, false);
}

export function TikTokUserInfoToJSONTyped(value?: TikTokUserInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'username': value['username'],
        'nickname': value['nickname'],
        'avatar': value['avatar'],
        'verified': value['verified'],
        'signature': value['signature'],
        'stats': TikTokUserInfoStatsToJSON(value['stats']),
    };
}

