/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TranscribeFromUrlResponseMeta
 */
export interface TranscribeFromUrlResponseMeta {
    [key: string]: any | any;
    /**
     * 
     * @type {number}
     * @memberof TranscribeFromUrlResponseMeta
     */
    duration?: number;
    /**
     * 
     * @type {string}
     * @memberof TranscribeFromUrlResponseMeta
     */
    author?: string;
    /**
     * 
     * @type {string}
     * @memberof TranscribeFromUrlResponseMeta
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TranscribeFromUrlResponseMeta
     */
    platform?: TranscribeFromUrlResponseMetaPlatformEnum;
}


/**
 * @export
 */
export const TranscribeFromUrlResponseMetaPlatformEnum = {
    Tiktok: 'tiktok',
    Instagram: 'instagram',
    Youtube: 'youtube'
} as const;
export type TranscribeFromUrlResponseMetaPlatformEnum = typeof TranscribeFromUrlResponseMetaPlatformEnum[keyof typeof TranscribeFromUrlResponseMetaPlatformEnum];


/**
 * Check if a given object implements the TranscribeFromUrlResponseMeta interface.
 */
export function instanceOfTranscribeFromUrlResponseMeta(value: object): value is TranscribeFromUrlResponseMeta {
    return true;
}

export function TranscribeFromUrlResponseMetaFromJSON(json: any): TranscribeFromUrlResponseMeta {
    return TranscribeFromUrlResponseMetaFromJSONTyped(json, false);
}

export function TranscribeFromUrlResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranscribeFromUrlResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'duration': json['duration'] == null ? undefined : json['duration'],
        'author': json['author'] == null ? undefined : json['author'],
        'title': json['title'] == null ? undefined : json['title'],
        'platform': json['platform'] == null ? undefined : json['platform'],
    };
}

export function TranscribeFromUrlResponseMetaToJSON(json: any): TranscribeFromUrlResponseMeta {
    return TranscribeFromUrlResponseMetaToJSONTyped(json, false);
}

export function TranscribeFromUrlResponseMetaToJSONTyped(value?: TranscribeFromUrlResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'duration': value['duration'],
        'author': value['author'],
        'title': value['title'],
        'platform': value['platform'],
    };
}

