/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCollectionRequest
 */
export interface UpdateCollectionRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the UpdateCollectionRequest interface.
 */
export function instanceOfUpdateCollectionRequest(value: object): value is UpdateCollectionRequest {
    return true;
}

export function UpdateCollectionRequestFromJSON(json: any): UpdateCollectionRequest {
    return UpdateCollectionRequestFromJSONTyped(json, false);
}

export function UpdateCollectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCollectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function UpdateCollectionRequestToJSON(json: any): UpdateCollectionRequest {
    return UpdateCollectionRequestToJSONTyped(json, false);
}

export function UpdateCollectionRequestToJSONTyped(value?: UpdateCollectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
    };
}

