/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateScriptRequest
 */
export interface UpdateScriptRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof UpdateScriptRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateScriptRequest
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateScriptRequest
     */
    category?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateScriptRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateScriptRequest
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateScriptRequest
     */
    status?: UpdateScriptRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateScriptRequest
     */
    scheduledDate?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateScriptRequest
     */
    platform?: UpdateScriptRequestPlatformEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateScriptRequest
     */
    publishedUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateScriptRequest
     */
    isThread?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateScriptRequest
     */
    threadParts?: Array<string>;
}


/**
 * @export
 */
export const UpdateScriptRequestStatusEnum = {
    Draft: 'draft',
    Published: 'published',
    Scheduled: 'scheduled',
    Sent: 'sent'
} as const;
export type UpdateScriptRequestStatusEnum = typeof UpdateScriptRequestStatusEnum[keyof typeof UpdateScriptRequestStatusEnum];

/**
 * @export
 */
export const UpdateScriptRequestPlatformEnum = {
    Tiktok: 'tiktok',
    Instagram: 'instagram',
    Youtube: 'youtube'
} as const;
export type UpdateScriptRequestPlatformEnum = typeof UpdateScriptRequestPlatformEnum[keyof typeof UpdateScriptRequestPlatformEnum];


/**
 * Check if a given object implements the UpdateScriptRequest interface.
 */
export function instanceOfUpdateScriptRequest(value: object): value is UpdateScriptRequest {
    return true;
}

export function UpdateScriptRequestFromJSON(json: any): UpdateScriptRequest {
    return UpdateScriptRequestFromJSONTyped(json, false);
}

export function UpdateScriptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateScriptRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'category': json['category'] == null ? undefined : json['category'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'status': json['status'] == null ? undefined : json['status'],
        'scheduledDate': json['scheduledDate'] == null ? undefined : json['scheduledDate'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'publishedUrl': json['publishedUrl'] == null ? undefined : json['publishedUrl'],
        'isThread': json['isThread'] == null ? undefined : json['isThread'],
        'threadParts': json['threadParts'] == null ? undefined : json['threadParts'],
    };
}

export function UpdateScriptRequestToJSON(json: any): UpdateScriptRequest {
    return UpdateScriptRequestToJSONTyped(json, false);
}

export function UpdateScriptRequestToJSONTyped(value?: UpdateScriptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'title': value['title'],
        'content': value['content'],
        'category': value['category'],
        'tags': value['tags'],
        'summary': value['summary'],
        'status': value['status'],
        'scheduledDate': value['scheduledDate'],
        'platform': value['platform'],
        'publishedUrl': value['publishedUrl'],
        'isThread': value['isThread'],
        'threadParts': value['threadParts'],
    };
}

