/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateNoteRequest
 */
export interface UpdateNoteRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof UpdateNoteRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateNoteRequest
     */
    content?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateNoteRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateNoteRequest
     */
    starred?: boolean;
}

/**
 * Check if a given object implements the UpdateNoteRequest interface.
 */
export function instanceOfUpdateNoteRequest(value: object): value is UpdateNoteRequest {
    return true;
}

export function UpdateNoteRequestFromJSON(json: any): UpdateNoteRequest {
    return UpdateNoteRequestFromJSONTyped(json, false);
}

export function UpdateNoteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNoteRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'starred': json['starred'] == null ? undefined : json['starred'],
    };
}

export function UpdateNoteRequestToJSON(json: any): UpdateNoteRequest {
    return UpdateNoteRequestToJSONTyped(json, false);
}

export function UpdateNoteRequestToJSONTyped(value?: UpdateNoteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'title': value['title'],
        'content': value['content'],
        'tags': value['tags'],
        'starred': value['starred'],
    };
}

