/* tslint:disable */
/* eslint-disable */
/**
 * Gen-C Scripts API
 * OpenAPI specification for key backend surfaces used by the dashboard. The documented endpoints power script CRUD flows in the dashboard and the YouTube idea seed generator. Responses follow the existing `{ success: ... }` envelope used by the legacy fetch helpers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddVideoToCollectionRequest,
  ApiVideosAddToCollectionPost200Response,
  ApiVideosCollectionPostRequest,
  BasicSuccessResponse,
  CollectionsResponse,
  CopyVideoRequest,
  CreateNoteRequest,
  CreateScriptRequest,
  ErrorResponse,
  GenerateIdeaSeedsRequest,
  GenerateIdeaSeedsResponse,
  MoveVideoRequest,
  NoteResponse,
  NotesResponse,
  ScriptResponse,
  ScriptsResponse,
  UpdateCollectionRequest,
  UpdateNoteRequest,
  UpdateScriptRequest,
  VideosResponse,
} from '../models/index';
import {
    AddVideoToCollectionRequestFromJSON,
    AddVideoToCollectionRequestToJSON,
    ApiVideosAddToCollectionPost200ResponseFromJSON,
    ApiVideosAddToCollectionPost200ResponseToJSON,
    ApiVideosCollectionPostRequestFromJSON,
    ApiVideosCollectionPostRequestToJSON,
    BasicSuccessResponseFromJSON,
    BasicSuccessResponseToJSON,
    CollectionsResponseFromJSON,
    CollectionsResponseToJSON,
    CopyVideoRequestFromJSON,
    CopyVideoRequestToJSON,
    CreateNoteRequestFromJSON,
    CreateNoteRequestToJSON,
    CreateScriptRequestFromJSON,
    CreateScriptRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GenerateIdeaSeedsRequestFromJSON,
    GenerateIdeaSeedsRequestToJSON,
    GenerateIdeaSeedsResponseFromJSON,
    GenerateIdeaSeedsResponseToJSON,
    MoveVideoRequestFromJSON,
    MoveVideoRequestToJSON,
    NoteResponseFromJSON,
    NoteResponseToJSON,
    NotesResponseFromJSON,
    NotesResponseToJSON,
    ScriptResponseFromJSON,
    ScriptResponseToJSON,
    ScriptsResponseFromJSON,
    ScriptsResponseToJSON,
    UpdateCollectionRequestFromJSON,
    UpdateCollectionRequestToJSON,
    UpdateNoteRequestFromJSON,
    UpdateNoteRequestToJSON,
    UpdateScriptRequestFromJSON,
    UpdateScriptRequestToJSON,
    VideosResponseFromJSON,
    VideosResponseToJSON,
} from '../models/index';

export interface ApiCollectionsCopyVideoPostRequest {
    copyVideoRequest: CopyVideoRequest;
}

export interface ApiCollectionsDeleteDeleteRequest {
    id: string;
}

export interface ApiCollectionsMoveVideoPostRequest {
    moveVideoRequest: MoveVideoRequest;
}

export interface ApiCollectionsUpdatePatchRequest {
    updateCollectionRequest: UpdateCollectionRequest;
}

export interface ApiNotesIdDeleteRequest {
    id: string;
}

export interface ApiNotesIdGetRequest {
    id: string;
}

export interface ApiNotesIdPutRequest {
    id: string;
    updateNoteRequest: UpdateNoteRequest;
}

export interface ApiNotesPostRequest {
    createNoteRequest: CreateNoteRequest;
}

export interface ApiScriptsIdDeleteRequest {
    id: string;
}

export interface ApiScriptsIdGetRequest {
    id: string;
}

export interface ApiScriptsIdPutRequest {
    id: string;
    updateScriptRequest: UpdateScriptRequest;
}

export interface ApiScriptsPostRequest {
    createScriptRequest: CreateScriptRequest;
}

export interface ApiScriptsYoutubeIdeasPostRequest {
    generateIdeaSeedsRequest: GenerateIdeaSeedsRequest;
}

export interface ApiVideosAddToCollectionPostRequest {
    addVideoToCollectionRequest: AddVideoToCollectionRequest;
}

export interface ApiVideosCollectionPostOperationRequest {
    apiVideosCollectionPostRequest: ApiVideosCollectionPostRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Copy a video to another collection.
     */
    async apiCollectionsCopyVideoPostRaw(requestParameters: ApiCollectionsCopyVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BasicSuccessResponse>> {
        if (requestParameters['copyVideoRequest'] == null) {
            throw new runtime.RequiredError(
                'copyVideoRequest',
                'Required parameter "copyVideoRequest" was null or undefined when calling apiCollectionsCopyVideoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/copy-video`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CopyVideoRequestToJSON(requestParameters['copyVideoRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BasicSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Copy a video to another collection.
     */
    async apiCollectionsCopyVideoPost(requestParameters: ApiCollectionsCopyVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BasicSuccessResponse> {
        const response = await this.apiCollectionsCopyVideoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a collection by id.
     */
    async apiCollectionsDeleteDeleteRaw(requestParameters: ApiCollectionsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BasicSuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCollectionsDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BasicSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete a collection by id.
     */
    async apiCollectionsDeleteDelete(requestParameters: ApiCollectionsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BasicSuccessResponse> {
        const response = await this.apiCollectionsDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List collections for the authenticated user.
     */
    async apiCollectionsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionsResponseFromJSON(jsonValue));
    }

    /**
     * List collections for the authenticated user.
     */
    async apiCollectionsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionsResponse> {
        const response = await this.apiCollectionsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Move a video between collections.
     */
    async apiCollectionsMoveVideoPostRaw(requestParameters: ApiCollectionsMoveVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BasicSuccessResponse>> {
        if (requestParameters['moveVideoRequest'] == null) {
            throw new runtime.RequiredError(
                'moveVideoRequest',
                'Required parameter "moveVideoRequest" was null or undefined when calling apiCollectionsMoveVideoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/move-video`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MoveVideoRequestToJSON(requestParameters['moveVideoRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BasicSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Move a video between collections.
     */
    async apiCollectionsMoveVideoPost(requestParameters: ApiCollectionsMoveVideoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BasicSuccessResponse> {
        const response = await this.apiCollectionsMoveVideoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a collection\'s metadata.
     */
    async apiCollectionsUpdatePatchRaw(requestParameters: ApiCollectionsUpdatePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BasicSuccessResponse>> {
        if (requestParameters['updateCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCollectionRequest',
                'Required parameter "updateCollectionRequest" was null or undefined when calling apiCollectionsUpdatePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/collections/update`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCollectionRequestToJSON(requestParameters['updateCollectionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BasicSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Update a collection\'s metadata.
     */
    async apiCollectionsUpdatePatch(requestParameters: ApiCollectionsUpdatePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BasicSuccessResponse> {
        const response = await this.apiCollectionsUpdatePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List notes for the authenticated user.
     */
    async apiNotesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotesResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/notes`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotesResponseFromJSON(jsonValue));
    }

    /**
     * List notes for the authenticated user.
     */
    async apiNotesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotesResponse> {
        const response = await this.apiNotesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete a note by id.
     */
    async apiNotesIdDeleteRaw(requestParameters: ApiNotesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BasicSuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiNotesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/notes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BasicSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete a note by id.
     */
    async apiNotesIdDelete(requestParameters: ApiNotesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BasicSuccessResponse> {
        const response = await this.apiNotesIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch a note by id.
     */
    async apiNotesIdGetRaw(requestParameters: ApiNotesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NoteResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiNotesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/notes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteResponseFromJSON(jsonValue));
    }

    /**
     * Fetch a note by id.
     */
    async apiNotesIdGet(requestParameters: ApiNotesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NoteResponse> {
        const response = await this.apiNotesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a note by id.
     */
    async apiNotesIdPutRaw(requestParameters: ApiNotesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NoteResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiNotesIdPut().'
            );
        }

        if (requestParameters['updateNoteRequest'] == null) {
            throw new runtime.RequiredError(
                'updateNoteRequest',
                'Required parameter "updateNoteRequest" was null or undefined when calling apiNotesIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/notes/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateNoteRequestToJSON(requestParameters['updateNoteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteResponseFromJSON(jsonValue));
    }

    /**
     * Update a note by id.
     */
    async apiNotesIdPut(requestParameters: ApiNotesIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NoteResponse> {
        const response = await this.apiNotesIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a note for the authenticated user.
     */
    async apiNotesPostRaw(requestParameters: ApiNotesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NoteResponse>> {
        if (requestParameters['createNoteRequest'] == null) {
            throw new runtime.RequiredError(
                'createNoteRequest',
                'Required parameter "createNoteRequest" was null or undefined when calling apiNotesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/notes`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateNoteRequestToJSON(requestParameters['createNoteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NoteResponseFromJSON(jsonValue));
    }

    /**
     * Create a note for the authenticated user.
     */
    async apiNotesPost(requestParameters: ApiNotesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NoteResponse> {
        const response = await this.apiNotesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List scripts for the authenticated user.
     */
    async apiScriptsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScriptsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scripts`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScriptsResponseFromJSON(jsonValue));
    }

    /**
     * List scripts for the authenticated user.
     */
    async apiScriptsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScriptsResponse> {
        const response = await this.apiScriptsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Delete a script.
     */
    async apiScriptsIdDeleteRaw(requestParameters: ApiScriptsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BasicSuccessResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiScriptsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scripts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BasicSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Delete a script.
     */
    async apiScriptsIdDelete(requestParameters: ApiScriptsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BasicSuccessResponse> {
        const response = await this.apiScriptsIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Fetch a script by id.
     */
    async apiScriptsIdGetRaw(requestParameters: ApiScriptsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScriptResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiScriptsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scripts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScriptResponseFromJSON(jsonValue));
    }

    /**
     * Fetch a script by id.
     */
    async apiScriptsIdGet(requestParameters: ApiScriptsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScriptResponse> {
        const response = await this.apiScriptsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a script.
     */
    async apiScriptsIdPutRaw(requestParameters: ApiScriptsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScriptResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiScriptsIdPut().'
            );
        }

        if (requestParameters['updateScriptRequest'] == null) {
            throw new runtime.RequiredError(
                'updateScriptRequest',
                'Required parameter "updateScriptRequest" was null or undefined when calling apiScriptsIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scripts/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateScriptRequestToJSON(requestParameters['updateScriptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScriptResponseFromJSON(jsonValue));
    }

    /**
     * Update a script.
     */
    async apiScriptsIdPut(requestParameters: ApiScriptsIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScriptResponse> {
        const response = await this.apiScriptsIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a script for the authenticated user.
     */
    async apiScriptsPostRaw(requestParameters: ApiScriptsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScriptResponse>> {
        if (requestParameters['createScriptRequest'] == null) {
            throw new runtime.RequiredError(
                'createScriptRequest',
                'Required parameter "createScriptRequest" was null or undefined when calling apiScriptsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scripts`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateScriptRequestToJSON(requestParameters['createScriptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScriptResponseFromJSON(jsonValue));
    }

    /**
     * Create a script for the authenticated user.
     */
    async apiScriptsPost(requestParameters: ApiScriptsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScriptResponse> {
        const response = await this.apiScriptsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate YouTube idea seeds from a transcript.
     */
    async apiScriptsYoutubeIdeasPostRaw(requestParameters: ApiScriptsYoutubeIdeasPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateIdeaSeedsResponse>> {
        if (requestParameters['generateIdeaSeedsRequest'] == null) {
            throw new runtime.RequiredError(
                'generateIdeaSeedsRequest',
                'Required parameter "generateIdeaSeedsRequest" was null or undefined when calling apiScriptsYoutubeIdeasPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/scripts/youtube-ideas`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateIdeaSeedsRequestToJSON(requestParameters['generateIdeaSeedsRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateIdeaSeedsResponseFromJSON(jsonValue));
    }

    /**
     * Generate YouTube idea seeds from a transcript.
     */
    async apiScriptsYoutubeIdeasPost(requestParameters: ApiScriptsYoutubeIdeasPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateIdeaSeedsResponse> {
        const response = await this.apiScriptsYoutubeIdeasPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a processed video to a collection.
     */
    async apiVideosAddToCollectionPostRaw(requestParameters: ApiVideosAddToCollectionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiVideosAddToCollectionPost200Response>> {
        if (requestParameters['addVideoToCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'addVideoToCollectionRequest',
                'Required parameter "addVideoToCollectionRequest" was null or undefined when calling apiVideosAddToCollectionPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/videos/add-to-collection`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddVideoToCollectionRequestToJSON(requestParameters['addVideoToCollectionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiVideosAddToCollectionPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Add a processed video to a collection.
     */
    async apiVideosAddToCollectionPost(requestParameters: ApiVideosAddToCollectionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiVideosAddToCollectionPost200Response> {
        const response = await this.apiVideosAddToCollectionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List videos for a collection.
     */
    async apiVideosCollectionPostRaw(requestParameters: ApiVideosCollectionPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideosResponse>> {
        if (requestParameters['apiVideosCollectionPostRequest'] == null) {
            throw new runtime.RequiredError(
                'apiVideosCollectionPostRequest',
                'Required parameter "apiVideosCollectionPostRequest" was null or undefined when calling apiVideosCollectionPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/videos/collection`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiVideosCollectionPostRequestToJSON(requestParameters['apiVideosCollectionPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideosResponseFromJSON(jsonValue));
    }

    /**
     * List videos for a collection.
     */
    async apiVideosCollectionPost(requestParameters: ApiVideosCollectionPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideosResponse> {
        const response = await this.apiVideosCollectionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
